name: Terraform Create Infrastructure

on:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  terraform-create:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_IN_AUTOMATION: "true"
      TF_CLI_ARGS_init: "-upgrade"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply (create all resources)
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Output ALB DNS
        working-directory: terraform
        run: terraform output -raw alb_dns_name
